desc 'Задача по умолчанию'
task default: 'test:load'

namespace :test do
  desc 'Вывод фразы Hello, world!'
  task :load do
    puts 'Hello, world!'
  end
end

# Homework 2
desc 'Display current date and time'
task :current_time do
  puts "Current time: #{Time.now}."
end
